apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: NodePort
  ports:
  - port: 8082 #port for messaging-service
    protocol: TCP
    name: http
  selector:
    app: messaging-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  selector:
    matchLabels:
      app: messaging-service
  replicas: 1
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
      - image: messaging-service
        name: messaging-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082 #port for messaging-service
      restartPolicy: Always