apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: NodePort
  ports:
  - port: 8082 #port for messaging-service
    protocol: TCP
    name: http
  selector:
    app: messaging-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  selector:
    matchLabels:
      app: messaging-service
  replicas: 1
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
      - image: dasha12678/messaging-service:latest
        name: messaging-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082 #port for messaging-service 
        env:
        - name: MONGO_URI
          value: "mongodb://${MONGO_URI}"
        - name: MONGO_DB
          value: "${MONGO_DB}"
        - name: SQS_REGION
          value: "${SQS_REGION}"   
        - name: SQS_URL
          value: "${SQS_URL}"
      restartPolicy: Always